
services:

  postgres:
    image: postgres:15-alpine
    container_name: catalago_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_produtos
    ports:
      - 5432:5432
    volumes:
       - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}